### ISSUE TITLE
Enable to use the official MySQL image

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#137]
## What

Currently, MOCO users need to prepare a customized MySQL image for MOCO. It takes a little work.
If we can use Docker's official MySQL images, it's easy and everyone is happy.

## How

1. Create a new container image that contains the `entrypoint` and `ping.sh`.
   (hereinafter, this is called `moco-static-files`(tentative name)).
2. Generate a StatefulSet such as the following from MOCO.

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      initContainers:
      # No changes
      - name: moco-conf-gen
        image: quay.io/cybozu/moco-conf-gen:0.3.0
        command:
        - /moco-conf-gen
        - --server-id-base=<id>

      # Add a new init container to copy static files to empty dir(static-files).
      - name: copy-static-files
        image: quay.io/cybozu/moco-static-files:X.Y.Z
        command:
        - cp 
        - /path/to/entrypoint
        - /path/to/ping.sh
        - /shared
        volumeMounts:
        - mountPath: /shared
          name: static-files

      # Mount the static-files and execute the copied entrypoint.
      - name: moco-init
        image: <user-specified mysql image>
        command:
        - /shared/entrypoint
        - init
        volumeMounts:
        - mountPath: /shared
          name: static-files

      containers:
      # Mount the static-files and execute the copied ping.sh.
      - name: mysqld
        image: <user-specified mysql image>
        livenessProbe:
          exec:
            command:
            - /shared/ping.sh
        volumeMounts:
        - mountPath: /shared
          name: static-files

      # Mount the static-files and execute the copied entrypoint.
      - name: agent
        image: <user-specified mysql image>
        command:
        - /shared/entrypoint
        - agent
        volumeMounts:
        - mountPath: /shared
          name: static-files

      volumes:
      - emptyDir: {}
        name: static-files
```

### Points to note

- `moco-static-files` image is rarely updated. So it will be set different version from MOCO.
- Unless the external specification changes of `moco-static-files`, the tag of the image in the existing StatefulSet must not be changed at MOCO's reconcile.
   - To prevent restarting MySQL pods due to MOCO updates.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions
