### ISSUE TITLE
Create users and databases declaratively

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#349]
## What

User creation, database creation and grant privileges accordingly are typical operations for MySQL.
We want to be able to do these operations declaratively.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by uqix** [comment]
How about pre-creating a database called app which is quite convenient in microservice architecture.

**Comment by ymmt2005** [comment]
@uqix Thanks for the info.
@masa213f @d-kuro I think this feature is worth doing.

**Comment by cvrajeesh** [comment]
It would be nice if we had this feature.

Example showing declarative DB creation in [cnpg](https://cloudnative-pg.io/documentation/preview/declarative_database_management/) 
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-example-one
spec:
  name: one
  owner: app
  cluster:
    name: cluster-example
  extensions:
  - name: bloom
    ensure: present
```
