### ISSUE TITLE
Readiness probes fail causing lots of restarts.

### ISSUE THREAD

**Issue by vanpelt** [cybozu-go/moco#380]
**Describe the bug**

I've been developing on a local 3 worker node kind cluster with a 3 replica MySQLCluster.  2 of the 3 databases are getting restarted every 30-60 minutes.  Looking into the agent logs I'm seeing:

```
{"level":"info","ts":1646250007.4211495,"logger":"agent","caller":"server/mysqld_health.go:63","msg":"replication threads are stopped"}
2022-03-02T19:40:07.422593Z moco-wandb-db-2 moco-agent error: "well: access" http_host="10.244.1.10:9081" http_method="GET" http_status_code=503 http_user_agent="kube-probe/1.21" protocol="HTTP/1.1" remote_ipaddr="10.244.1.1" request_id="6496ba49-a792-c429-e5a9-e1a8f5bc725a" request_size=0 response_size=31 response_time=0.110781667 type="access" url="/readyz"
```

Looking at the pod spec, the readiness probe should need to fail 3 consecutive times before it becomes unhealthy, but the agent logs aren't showing me 3 consecutive 503's.  Here's a snippet of the events happening in the cluster:

```
3m2s        Warning   Unhealthy   pod/moco-wandb-db-2          Readiness probe failed: HTTP probe failed with statuscode: 503
3m          Warning   Unhealthy   pod/moco-wandb-db-0          Readiness probe failed: HTTP probe failed with statuscode: 503
15m         Warning   Unhealthy   pod/moco-wandb-db-2          Readiness probe failed: Get "http://10.244.1.10:9081/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
16m         Warning   Unhealthy   pod/moco-wandb-db-1          Liveness probe failed: Get "http://10.244.2.13:9081/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

In all likelyhood this is likely just something funky about my dev environment (I'm running an M1 mac so it's likely emulating the amd64 arch), but I would be curious on ideas for how to better debug the root cause here.  Here's my cluster spec:

```yaml
apiVersion: v1
items:
- apiVersion: moco.cybozu.com/v1beta1
  kind: MySQLCluster
  metadata:
    finalizers:
    - moco.cybozu.com/mysqlcluster
    generation: 1
    name: wandb-db
    namespace: wandb
  spec:
    backupPolicyName: null
    collectors:
    - engine_innodb_status
    - info_schema.innodb_metrics
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - mysql
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - wandb-db
              topologyKey: kubernetes.io/hostname
        containers:
        - image: quay.io/cybozu/mysql:8.0.28
          name: mysqld
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
    replicas: 3
    serverIDBase: 258151394
    startupDelaySeconds: 3600
    volumeClaimTemplates:
    - metadata:
        annotations:
          helm.sh/resource-policy: keep
        name: mysql-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
``` 

**Environments**
- Version: latest
- OS: mac, kind

**To Reproduce**

**Expected behavior**

**Additional context**
