### ISSUE TITLE
Error on new cluster boot: secret "moco-mycluster-grpc" not found

### ISSUE THREAD

**Issue by mplewis** [cybozu-go/moco#426]
**Describe the bug**

I am trying to start a new Moco cluster. However, the pod does not start successfully, and I see the following error event on the pod:

```
MountVolume.SetUp failed for volume "grpc-cert" : secret "moco-mycluster-grpc" not found
```

My cluster config is as follows:

```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: mycluster
  namespace: default
spec:
  backupPolicyName: daily
  podTemplate:
    metadata: {}
    spec:
      containers:
      - image: quay.io/cybozu/mysql:8.0.28
        name: mysqld
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```

**Environments**

- Version: `version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`
- OS: Linux (DigitalOcean Managed Kubernetes Cluster)

**To Reproduce**

* Start a [managed Kubernetes cluster on DigitalOcean](https://www.digitalocean.com/products/kubernetes)
* Install Cert-Manager using Helm release 1.8.2
* Install Moco using Helm release 0.2.3
* Create the cluster from the YAML above

**Expected behavior**

The cluster creates without error.

Please let me know if you need any additional info to help debug this.
