### ISSUE TITLE
Backup to Google Cloud Storage

### ISSUE THREAD

**Issue by filiprafaj** [cybozu-go/moco#427]
Hello, I am trying and failing to store backups to Google Cloud Storage.

I have set up [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) to give the k8s service account the permissions to access the bucket.

I have also tried defining the _AWS_ACCESS_KEY_ID_ and _AWS_SECRET_ACCESS_KEY_ variables.

Still I get
`Error: failed to take a full dump: failed to put dump.tar: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.`

Is there anybody who made backups to GCS working? 

Thank you!

**Comment by ymmt2005** [comment]
Backup to GCS is not supported now.
It can be added by implementing Bucket interface for GCS in this package.
https://github.com/cybozu-go/moco/tree/main/pkg/bucket

We are welcome to a pull request for adding GCS support.

**Comment by d-kuro** [comment]
@filiprafaj 
GCS supports the S3 compatibility API. (Sorry, I have not verified this.)
Could you please refer to the documentation and try again?

refs: 
* https://cloud.google.com/storage/docs/interoperability#xml_api
* https://vamsiramakrishnan.medium.com/a-study-on-using-google-cloud-storage-with-the-s3-compatibility-api-324d31b8dfeb

If it still doesn't work, it would be helpful if you could report it again, including the definition of BackupPolicy 🙏 
https://cybozu-go.github.io/moco/usage.html#backuppolicy

**Comment by filiprafaj** [comment]
Hi @d-kuro , I have tried now with **interoperability credentials** and I am getting:

`
Error: failed to take a full dump: failed to put dump.tar: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. failed to take a full dump: failed to put dump.tar: operation error S3: PutObject, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. 
`

the backup file looks like this:

```
apiVersion: moco.cybozu.com/v1beta2
kind: BackupPolicy
metadata:
  namespace: default
  name: daily
spec:
  schedule: "@daily"
  jobConfig:
    serviceAccountName: moco-test-mysqlcluster
    env:
    - name: AWS_ACCESS_KEY_ID
      value: ***
    - name: AWS_SECRET_ACCESS_KEY
      value: ***
    bucketConfig:
      bucketName: ***
      endpointURL: https://storage.googleapis.com
    workVolume:
      emptyDir: {}
    memory: 1Gi
    maxMemory: 1Gi
    threads: 1
```
