### ISSUE TITLE
BackupPolicy should provide a way to use fsGroup securityContext

### ISSUE THREAD

**Issue by NaPs** [cybozu-go/moco#438]
When using BackupPolicy with ephemeral volumes, backups can fail with a permission denied error trying to write dump to the volume. This is because moco-backup run as uid 10000 and persistent volume is created with a root folder owned by root.

BackupPolicy CR should provide a way to set an fsGroup or an fsGroup should be hardcoded in Cronjob definition to prevent this problem.

**Comment by NaPs** [comment]
For those who are looking for a way to workaround this problem, here is our solution using a Kyverno policy to mutate CronJob's Pods on the fly:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-add-fsgroup-moco-backup-jobs
spec:
  rules:
  - name: add-fsgroup-moco-backup-jobs
    match:
      resources:
        kinds:
        - Pod
        selector:
          matchLabels:
            app.kubernetes.io/created-by: moco
            app.kubernetes.io/name: mysql-backup
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            +(fsGroup): 10000
```
