### ISSUE TITLE
argocd, cert manager  and MOCO gRPC CA 

### ISSUE THREAD

**Issue by Links2004** [cybozu-go/moco#459]
**Describe the bug**
cert manager needs "0m0s" at the end of `duration` `renewBefore` for MOCO gRPC CA.
if this is not the case then cert manager will patch the CR.
this is problematic for argocd since it tries to keep the CR in sync with the moco.yaml.
as a result argocd and cert manager will patch the CR in a endless loop.

![image](https://user-images.githubusercontent.com/974709/190913618-9979fbc4-8e2f-4cea-bcb1-b5775ade4a3c.png)

**Environments**
- Version: latest
- OS:

**To Reproduce**
deploy https://github.com/cybozu-go/moco/releases/latest/download/moco.yaml via argocd

**Expected behavior**
 `duration` `renewBefore` are set correctly in the released moco.yaml

**Comment by masa213f** [comment]
Thank you for the report! I'll fix it.
Please set `ignoreDifferences` until the next release.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  ...
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
```
