### ISSUE TITLE
How to create multiple MySQLClusters in the same namespace

### ISSUE THREAD

**Issue by uqix** [cybozu-go/moco#464]
According to the doc:

```yaml
  volumeClaimTemplates:
  # At least a PVC named "mysql-data" must be defined.
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

> At least a PVC named "mysql-data" must be defined.

I wonder if it's possible to create multiple MySQLClusters in the same namespace.
