### ISSUE TITLE
MySQL Pods are not created when the length of MySQLCluster name is 48 or more

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/moco#502]
**Describe the bug**
MySQL Pods are not created when the length of MySQLCluster name is 48 or more.

**Environments**
- Version: MOCO v0.14.1、Kubernetes 1.24.9

**To Reproduce**
Apply the following manifest:

```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: mycluster-12345678901234567890123456789012345678
spec:
  podTemplate:
    spec:
      containers:
      - image: quay.io/cybozu/mysql:8.0.28
        name: mysqld
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

Then the resource is successfully created, but MySQL pods iare not created.
The following error is recorded in the StatefulSet's event.

```
$ kubectl describe sts -n sandbox moco-mycluster-12345678901234567890123456789012345678 | tail
  StorageClass:  topolvm-flash1-xfs
  Labels:        <none>
  Annotations:   <none>
  Capacity:      5Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  31s                 statefulset-controller  create Claim mysql-data-moco-mycluster-12345678901234567890123456789012345678-0 Pod moco-mycluster-12345678901234567890123456789012345678-0 in StatefulSet moco-mycluster-12345678901234567890123456789012345678 success
  Warning  FailedCreate      10s (x13 over 31s)  statefulset-controller  create Pod moco-mycluster-12345678901234567890123456789012345678-0 in StatefulSet moco-mycluster-12345678901234567890123456789012345678 failed error: Pod "moco-mycluster-12345678901234567890123456789012345678-0" is invalid: metadata.labels: Invalid value: "moco-mycluster-12345678901234567890123456789012345678-584f97cbf9": must be no more than 63 characters
```

**Expected behavior**
Deny creation of MySQL resource by the validation webhook, when the length of MySQLCluster name is 48 or more.

**Additional context**
