### ISSUE TITLE
Does operator and CR not support adding environment variables，such as time_zone

### ISSUE THREAD

**Issue by sona-yuan** [cybozu-go/moco#720]
## What

Does operator and CR not support adding environment variables，such as time_zone
## How

containers:
      - name: mysqld
         env:
         - name: TZ
           value: "Asia/Shanghai"

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by YZ775** [comment]
@sona-yuan 
I confirmed the env written in MySQLCluster is propagated to its Pods.


`MySQLCluster.spec.podTemplate` is [PodSpecApplyConfiguration](https://pkg.go.dev/k8s.io/client-go/applyconfigurations/core/v1#PodSpecApplyConfiguration). Please see [here](https://cybozu-go.github.io/moco/crd_mysqlcluster_v1beta2.html#podtemplatespec) for detail. 



```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  namespace: sandbox
  name: test
spec:
  replicas: 3
  podTemplate:
    spec:
      containers:
      - name: mysqld
        image: ghcr.io/cybozu-go/moco/mysql:8.4.0
        env:
          - name: TZ
            value: "Asia/Shanghai"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

```console
$ kubectl get pod -n sandbox moco-test-0 -oyaml | yq .spec.containers[0].env
- name: TZ
  value: Asia/Shanghai
```

```console
$ kubectl exec -n sandbox moco-test-0 mysqld -it -- bash
Defaulted container "mysqld" out of: mysqld, agent, slow-log, copy-moco-init (init), moco-init (init)
groups: cannot find name for group ID 10000
I have no name!@moco-test-0:/$ 
I have no name!@moco-test-0:/$ echo $TZ
Asia/Shanghai
I have no name!@moco-test-0:/$ 
```
