### ISSUE TITLE
How to set up backup policy?

### ISSUE THREAD

**Issue by shinebayar-g** [cybozu-go/moco#768]
Hi, first of all, great work on the project! 👏 

I successfully deployed the moco operator and bootstrapped my first cluster. However, I can't quite figure out the backup part.
I've read through the entire documentation and it seems backup is covered [here](https://cybozu-go.github.io/moco/usage.html#backup-and-restore) and [here](https://cybozu-go.github.io/moco/backup.html).

In the Usage page, it says we need kubernetes service account. But it's unclear which roles should be granted on that service account, if any.
Also, documentation example uses:

```yaml
kind: BackupPolicy
metadata:
  namespace: backup
  name: daily
```

and

```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  namespace: default
  name: foo
spec:
  backupPolicyName: daily
```

But it doesn't work and gives the following error.

```json
{"level":"error","ts":"2025-01-11T20:55:08Z","msg":"Reconciler error","controller":"mysqlcluster","controllerGroup":"moco.cybozu.com","controllerKind":"MySQLCluster","MySQLCluster":{"name":"db1","namespace":"moco-dbs"},"namespace":"moco-dbs","name":"db1","reconcileID":"faed559c-4f35-4880-9746-daed1a9ca49f","error":"failed to get backup policy moco-dbs/daily: BackupPolicy.moco.cybozu.com \"daily\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

It seems `BackupPolicy` and `MySQLCluster` have to be in the same namespace?

I tried the following syntax and it seems to be working. At least error is gone.

```yaml
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  namespace: default
  name: foo
spec:
  backupPolicyName: backup/daily
```

But there's no cronjob created. Probably because I'm not using any roles on the service account. But it's not documented anywhere. Could you help me set up the backup policy?

Currently there's no error or events that can indicate anything.
