### ISSUE TITLE
What time to specify for `restorePoint`

### ISSUE THREAD

**Issue by 0xAX** [cybozu-go/moco#771]
Hello,

I have installed two different MySQL clusters with 1 replicas each and setup usual async replication between them. I am collecting backup only from the second instance. Now I am trying to test restore from the backup but the first instance. 

My manifest is:

```
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  name: mysql-primary-deployment
spec:
  replicas: 1
  mysqlConfigMapName: primary-mycnf
  restore:
    sourceName: moco-mysql-secondary-deployment-0
    sourceNamespace: testing
    restorePoint: "2025-01-22T19:15:01Z"
    jobConfig:
      serviceAccountName: moco-mysql-primary-deployment
      env:
      - name: AWS_ACCESS_KEY_ID
        value: console
      - name: AWS_SECRET_ACCESS_KEY
        value: console123
      bucketConfig:
        bucketName: mysql-backup
        region: us-east-1
        endpointURL: http://minio:9000
        usePathStyle: true
      workVolume:
        emptyDir: {}
  podTemplate:
    spec:
      containers:
      - name: mysqld
        image: ghcr.io/cybozu-go/moco/mysql:8.4.3
        resources:
          requests:
            memory: "12Gi"
            cpu: "4"
          limits:
            memory: "12Gi"
            cpu: "4"
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
```

In the minio I have - 

![Image](https://github.com/user-attachments/assets/ddc272f1-d24c-439c-88f4-059d9ea4fd91)

I tried both values for the `restorePoint` local and UTC:

- `2025-01-22T19:15:01Z`
- `2025-01-22T19:15:01Z`

although in the logs of the `testing/moco-restore-mysql-primary-deployment-nsnck:restore` I see:

```
│ {"level":"info","ts":"2025-01-22T15:05:36Z","msg":"waiting for a pod to become ready","name":"moco-mysql-primary-deployment-0"}                                            │
│ {"level":"info","ts":"2025-01-22T15:05:41Z","msg":"waiting for the mysqld to become ready","name":"moco-mysql-primary-deployment-0"}                                       │
│ Error: no available backup                                                                                                                                                 │
│ no available backup                                                                                                                                                        │
│ Stream closed EOF for testing/moco-restore-mysql-primary-deployment-nsnck (restore)      
```

What time it expects? Is it expected to work that backup is taken from one instance and we try to restore db on the another one?
